### ISSUE TITLE
Verbose Redis Config

### ISSUE THREAD

**Issue by Finkman** [jboxberger/synology-gitlab#1]
Config of Redis-Server is very verbose. It wakes up every 5 minutes and writes to the log, causing the NAS not to go to hibernation and keeps the HDD up.

**Comment by jboxberger** [comment]
you mean this behavour here?
13:43:25 [1] 12 Jan 13:43:25.013 \* 10 changes in 300 seconds. Saving...
13:43:25 [1] 12 Jan 13:43:25.013 \* Background saving started by pid 93
13:43:25 [93] 12 Jan 13:43:25.073 \* DB saved on disk
13:43:25 [93] 12 Jan 13:43:25.073 \* RDB: 0 MB of memory used by copy-on-write
13:43:25 [1] 12 Jan 13:43:25.115 \* Background saving terminated with success

**Comment by Finkman** [comment]
_Exactly!_
Is it something _redis_-specific? I think it would be a great approvement to allow hdd-sleep modes with a mod.

**Comment by jboxberger** [comment]
As far as i can see it's a redis issue. This Activity comes from redis itself and is called "SNAPSHOTTING" and saves every 300 Seconds if more than 10 Database Changes are made. 
See "SNAPSHOTTING":  https://raw.githubusercontent.com/antirez/redis/2.8/redis.conf

The "SNAPSHOTTING" is used to keep redis persistant (http://redis.io/topics/persistence) so turning it off may bring you data loss on power loss or process kill. "SNAPSHOTTING" os optional, i make a shot tutorial how you can turn it off, if you want to. 

I think the better question is: where do the changes come from?

I'll try to find the answer.

**Comment by Finkman** [comment]
Ich denke mal, Du kannst auch deutsch. :-)

Ist es vielleicht irgendein Background-Job im GitLab? Dort werden Graphen und Statistiken über die Aktivitäten generiert...

Ich hatte auch mal versucht, das Log bzw. das redis-db-file auf einen USB-Stick auszulagern, aber leider erfolglos. Vielleicht bist Du da aber fitter als ich.

Überhaupt... vielen Dank für das Package!

**Comment by Finkman** [comment]
Hi,
konntest Du inzwischen in Erfahrung bringen, warum Gitlab alle 5min was macht? Ich würde das gerne abstellen.

**Comment by Finkman** [comment]
I have opened a support-issue on gitlab:
https://gitlab.com/gitlab-com/support-forum/issues/521

**Comment by jboxberger** [comment]
Sorry i forgot to post the results :-)

Be warned!: you may loose your data persitance (i can't evaluate the follow) so maybe you think about diabling the snapshottinmg twice.

**Enter your redis container (ssh):**
_docker exec -it $(docker ps | grep "quay.io/sameersbn/redis" | awk '{print $1}') bash_

**Modify the reds config:**
_vi /etc/redis/redis.conf_

**Disable all save lines by adding a hash at the beginning and enter one empty save "" line to kill all prevoius snapshots** 
_save ""
#save 900 1
#save 300 10
#save 60 10000_

If you run in errors yo may need to set stop-writes-on-bgsave-error no.

Please report your experience.

**Comment by Finkman** [comment]
Thank you for that.

I'll figure out if I can -alternatively- set the save timout to an higher threshold value. To do a snapshot once a day in average.

**Comment by jboxberger** [comment]
Everything woks fine? 
Can we close the issue?
