### ISSUE TITLE
It is not clear how to install synology-gitlab package?

### ISSUE THREAD

**Issue by yavuzdoganc** [jboxberger/synology-gitlab#10]
install procedure is unclear to me, via docker registry or via synology package center?
If I look at readme, there is nothing explaining the install procedure. 
Clone your repository within synology DSM and run the scripts manually?

**Comment by jboxberger** [comment]
Thanks for your inquiry, i thought this is clear. I will make a little tutorial for the future.

Just download the SPK and install it with the Synology Package-Manager by pushing the "Manual Installation" Button
![01](https://cloud.githubusercontent.com/assets/1545845/20639878/1c267f86-b3d0-11e6-98ee-15e4981f22dd.PNG)

If you run into an error you need to allow the installation from "other" sources. I just cant get the signature process running :-(.

![image](https://cloud.githubusercontent.com/assets/1545845/20639911/528788ea-b3d0-11e6-9490-6f55cc8d71a8.png)

If some depencency package are missing, you will get notifications.

Kind Reagrds

**Comment by yavuzdoganc** [comment]
Thank you for the fast and clear response, as you mentioned I've run into the signature missing issue which was solved by your hint.

Kind Regards.
