### ISSUE TITLE
HTTPS and SSL_SELF_SIGNED Options During Installation

### ISSUE THREAD

**Issue by helmut-steiner** [jboxberger/synology-gitlab#13]
Hey,
I just wondered if you can include the GITLAB_HTTPS and SSL_SELF_SIGNED option during the installation process? It should just be one additional step in the update/installation process and not much work. Additionally the port of the container must be set to 443 instead of 80 for GITLAB_HTTPS.
This makes it easier for people that want to run the webinterface through HTTPS. Now this settings have to be edited after every update.
Cheers,
Helmut

**Comment by jboxberger** [comment]
Hi Helmut,

i will see on this weekend what i can do for you and give you Feedback.

Kind Regards

**Comment by jboxberger** [comment]
Hi Helmut,

i checking your issue right now.  How about a dropdown with following options:

HTTP  => container_port = 80
HTTPS => Set GITLAB_HTTPS=true, container_port = 443
HTTPS-SELF-SIGNED  => Set GITLAB_HTTPS=true, container_port = 443, SSL_SELF_SIGNED=true 

Would this solve your issue?

Kind Regards

**Comment by helmut-steiner** [comment]
Hey Juri,
Yeah, that totally does it for me! Thanks a lot!
Kind regards

**Comment by agherzan** [comment]
Any news on this? Is it supported now?

**Comment by jboxberger** [comment]
Hello guys,

i solved the problem, but not the way you expected. I've implemented in the new version [ >10.1.1 ] a feature which saves custom ENVIRONMENT variables and restores them to the new version. So you do not have to fix your config after every update. 

Sorry for the long time you had to wait, but i had to get more into it before i could solve this issue.

Please let me know if this worked for you.

Kind Regards

**Comment by helmut-steiner** [comment]
Hey Juri,
That works for me! I'll try it once I have updated and let you know if everything works.
Thanks!

**Comment by helmut-steiner** [comment]
I had some issues with my gitlab instance on our production server. It was just not reachable anymore after a hyper backup of the docker and mariadb packages. I tried a lot to get it back working but without success.
Upgrading gitlab to your new version solved not only the environment problem, but also the whole gitlab instance not being reachable! I guess it was a ressource related issue and now that the sidekiq tasks variable is working again and the tasks are back to the amount I want them (not 25 as set as default) everything is up and running again.

Thank you Juri!

**Comment by jboxberger** [comment]
Hi Helmut, 
there are some news on my second Gitlab Project. Just wanted to let you know.

https://github.com/jboxberger/synology-gitlab-jboxberger

![grafik](https://user-images.githubusercontent.com/1545845/37124089-29160944-2267-11e8-9891-eac563421085.png)

Kind Regards
