### ISSUE TITLE
Unable to run after installation

### ISSUE THREAD

**Issue by paulo-maia** [jboxberger/synology-gitlab#14]
Hi and thank you for the package.

I am unable to run gitlab after the installation. The install process went smoothly but afterwards, when I hit run, nothing happens. 
The docker manager is saying that no container has been created... 
I tried uninstalling and reinstalling twice now to no avail...

My configuration:
Model: RS815+
CPU:   Intel Atom C2538
DSM version:  6.0.2-8451 Update 9

I really wanted to try this package since the official synology one is way out-of-date.

Kind regards!

**Comment by jboxberger** [comment]
Hi,

it sounds like there are old images in the Docker Container. You can see the on the Image Tab.
![image](https://cloud.githubusercontent.com/assets/1545845/24273970/bcab5f7e-1025-11e7-989e-234cb1c35491.png)

You can try to remove them via docker Manager or if you have trouble removing old images you can try this. Fist stop all useless images. Then login with ssh as root on your synology and enter this command

docker rmi $(docker images -q --filter dangling=true)

If the old images are gone you can reinstall the synology package and everything should work fine. If it doesn't help, you can uninstall the synology package (keeping all your data) and reinstall the package again (please don't forget to save your database credentials first).

Please let me know if this helped you.

Kind Regards

**Comment by paulo-maia** [comment]
Hi @jboxberger , I didn't have any old images in the docker container.
I think the problem was simply that I wasn't giving it enough time to initialize gitlab (I later found out the log for the container and was able to see that gitlab was still initializing stuff).

I updated the DSM and installed the latest version of your package (gitlab 9.0.0) and everything is running smoothly.
Thanks again for your help and for this package :) Now to the painful process of migrating more than 100 projects from gitlab 6...

Kind regards,

**Comment by jboxberger** [comment]
Hi paulo-maia,
sorry for my late feedback, i saw that you issue has already been solved 👍.

Kind Regards
