### ISSUE TITLE
Can't setup gitlab - Missing gitlab container after installing

### ISSUE THREAD

**Issue by tobidemski** [jboxberger/synology-gitlab#19]
Hey Juri,

currently i am not able to install the gitlab image with my ds916+.
I don't know why but i think the problem is the newest firmware.
Can you confirm this?

Model: DS916+
Version: DSM 6.1.3-15152 Update 4
DSM-Datum: 2017/09/01

Tried to install your latest.spk and different other versions. Reinstalled mariadb 5 and tried a full clean install but nothing work.

Do you have any ideas?

Best regards
D4rkiii

**Comment by jboxberger** [comment]
Did it worked? :-)

**Comment by tobidemski** [comment]
i trying to figure it out.. I found a way to get it run (with just the default configuration).
But if im trying to set some configuration for my environment i lost the container and the image won't run.

**Comment by jboxberger** [comment]
May i can help. What Kind of Configuration do you mean?
1) Database Credentials?
2) Configuration during Setup?
3) Manually set ENVIRONMENT Variables in the docker container after Setup?

**Comment by tobidemski** [comment]
Im trying to install the gitlab package with my custom values like hostname and mail config data. But this do let me start the container after the installation because the container is missing (gitlab & redis image are downloaded). Just the redis container is running and the gitlab container is missing.

Now im trying to install the gitlab with standard values and edit it hopefully after the successfully installation.

**Comment by tobidemski** [comment]
Okay.. my gitlab is running now. At first i just installed the gitlab 9.5.2 with the default configuration except the database credentials. (Now the gitlab container appears under the container tab in the docker app) Now i configured the docker container with my data like gitlab host, port and mail stuff.

Do you have an explanation for this behavior? :/

**Comment by jboxberger** [comment]
Ah ok great, i just typed a big roman how to handle boken images in docker. Ok the main task is done here. can you logon to gitlab?

If you click in Docker -> Container -> "synology_gitlyb" -> Details (Tab) -> Protocol (Tab) you can see what went wrong during Container start up. 

What kind of error do you get during Container bootup in the Logs?

Since i use the common samersbeen package you can try your luck by googling the error first. My SPK Package is just a wrapper for the samersbeen docker image fo unexpireinced user just to get them started. So if you're more expirienced in docker maybe you can use the docker directly wihout my package wrapping. Here you're completely free with the configuration. More Infos are here: https://hub.docker.com/r/sameersbn/gitlab/

Let me know what kind of error you got an i try to help.

Kind Reagrds

**Comment by tobidemski** [comment]
The problem with my previous installation was, that there wasn't any container in docker (just the downloaded image). So it was not possible to see what kind of error the installation broke.

Now i am able to login into gitlab and use it with no problems.
I have not much experience in docker thats why i am using your wrapper :/

**Comment by jboxberger** [comment]
Ah ok, so the youre correct here. You can change all Settings in the Docker Container at any time.

Just: click in Docker -> Container -> "synology_gitlyb" -> Actions (Tab) -> Stop. Now you can hit the edit tab and go to the environment variables and modify the package you like. 

Before modifying you can hit Docker -> Container -> "synology_gitlyb" -> Settings -> Export to save the configuration just in case you want to restore the prevous configuration.

All available ENVIRONMENT Variables you can find here:
https://hub.docker.com/r/sameersbn/gitlab/

**Comment by jboxberger** [comment]
Aber wir können auch auf deutsch reden :-)) habe gerade erst "DSM-Datum" gesehen.

**Comment by tobidemski** [comment]
Ach nice!... Ja aber normalerweise sollte ja alles über den Wizard laufen und nicht im nachhinein. Bisschen blöd gerade aber habe dann doch noch einen Weg gefunden., Danke dir für die Hilfe!

**Comment by jboxberger** [comment]
Kein Problem :-).

im Wizzard sind nur die Basics, der sollte eigentlich problemlos durchlaufen. Ich vermute das der download beim ersten mal fehlgeschlagen ist und ein fehlerhaftes Image "Abbild" abgelegt hat und der Container damit nicht starten konnte. Wenn du mir die Einstellungen (anonymisiert) durchgibst mit denen du Probleme hattest kann ich das mal prüfen.

Gruss

**Comment by tobidemski** [comment]
Ne habe in Docker geschaut. Ein Abbild (2GB) wurde heruntergeladen, genauso wie das für Redis, jedoch wurde nur ein Redis Container davon erstellt aber kein Gitlab Container. Nach der deinstallation wurden immer alle Container und Images gelöscht.

Ich weiß leider nicht genau welche Stelle den Fehler verursacht hat. Habe Test weise eine Installation vorgenommen welche nur meine DB Credentials beinhaltet hat welche dann auch funkrioniert hatte. Sobald ich Hostname etc. mit angegeben habe, kam nach dem Download des Images nichts mehr.

Habe also eigentlich keine speziellen Einstellungen vorgenommen.
DB Name & User: Default Werte (gitlab)
Gitlab Port: 80 & SSH auf Default (30001)
Host: gitlab.meinedomain.de
SMTP_HOST / DOMAIN: mail.meinedomain.de
SMTP Port: 25

Das war es auch schon....


Gruß

**Comment by tobidemski** [comment]
Hey,

hast du schon auf die neuste Version geupdated? Habe mit deiner bat Datei und Anpassungen an der Common / INFO File mir die neuste Version generiert und anschließend einen clean Install gemacht. habe jedoch wieder das Problem das der Container nicht vom Image erstellt wird (nur der synology_gitlab container nicht. Redis ist da.)
Wenn ich ein Container mit den Settings mache klappt auch gitlab wieder nur ist das nach jedem Update irgendwie blöd das selber zu machen :/
Ist in deinem Script evtl. was kaputt was nach Version X auftritt?

Grüße

/Edit:

Habe nachdem ich den HOST auf localhost gelassen habe, es erfolgreich hinbekommen das er den Container erstellt. Habe dann manuell nur noch den Host anpassen müssen bevor ich dann gitlab laufen lassen habe.

**Comment by jboxberger** [comment]
Hi das Update habe ich soeben gemacht... ist der Server den von außen auch über den anderen DNS-
Namen erreichbar? Ich habe auch einen anderen HOST aber das Problem habe ich nicht. Eventuell hast du  mehrere Images unter dem Namen laufen... 

If you have trouble removing old images you can try this. Fist stop all useless images. Then login with ssh as root on your synology and enter this command

docker rmi $(docker images -q --filter dangling=true)

If the old images are gone you can reinstall the synology package and everything should work fine. If it doesn't help, you can uninstall the synology package (keeping all your data) and reinstall the package again (please don't forget to save your database credentials first).

**Comment by tobidemski** [comment]
Wenn ich in die Docker Übersicht gehe habe ich immer nur das aktuelle Image / Container.
Mein Host ist auch von außen erreichbar und wenn ich nach der Installation den Host von localhost ändere funktioniert auch anschließend alles.
Dann muss ich wohl erstmal mit dem Workaround leben.
