### ISSUE TITLE
SMTP configuration for gmail doesn't work

### ISSUE THREAD

**Issue by agherzan** [jboxberger/synology-gitlab#21]
I added gmail configuration for SMTP but testing it from the rail console fails with:
```
EOFError: end of file reached
```

**Comment by jboxberger** [comment]
Hi agherzan,

i tried almost every combination with the environment variables but without success.  Studying the description below i found out that three ENVIRONMENT variables need to be set.

SMTP_AUTHENTICATION=login
SMTP_ENABLE_STARTTLS_AUTO=true
SMTP_TLS=false

But setting them took me to the "OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed" error.

In the hints there is following message "If you encounter authentication errors, ensure you have [allowed less secure apps to access the account](https://support.google.com/accounts/answer/6010255) or try turning on 2-step validation  and using [an application password](https://support.google.com/mail/answer/185833)."
Source: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/smtp.md

Maybe you can check your Gmail Security settings? Please give me a feedback if this works for you.

Kind Regards

**Comment by agherzan** [comment]
I will keep in mind to retest it when I reinstall it. Currently because all of the issues that I got into I dropped the idea of using this.
