### ISSUE TITLE
Support for 918+?

### ISSUE THREAD

**Issue by justinhelmer** [jboxberger/synology-gitlab#25]
Hello, thank you for taking the time to maintain a package with latest gitlab/redis.

I am attempting to install the spk, but get an error that it is not supported on my DSM version or architecture.

Running latest DSM (6.1). The base package here: https://www.synology.com/en-us/dsm/packages/Docker-GitLab works for me.

Any help would be appreciated.

**Comment by jboxberger** [comment]
Yes support will come with the new package.

**Comment by jboxberger** [comment]
I added the support to GitLab-10.1.1 (latest). Hope this helps. I own the DS918+ by myself so this will be also supported in any future release :-).

I close the ticket, if something is wrong, feel free to reopen it anytime. 

Kind Regards and Happy New Year!
