### ISSUE TITLE
time keeping

### ISSUE THREAD

**Issue by Hardcore-fs** [jboxberger/synology-gitlab#27]
would it be possible to add an "NTP" client  to the synology container.

since the time zone info for this implementation is incorrect, depending on where in the world you are.

currently it seems GIT pushes are not showing the "local" time.

**Comment by jboxberger** [comment]
Hi,

have you tried to set the environment variable **GITLAB_TIMEZONE** in your docker container? Does this help? 

GITLAB_TIMEZONE | Configure the timezone for the gitlab application. This configuration does not effect cron jobs. Defaults to UTC. See the list of acceptable values.
Source: https://hub.docker.com/r/sameersbn/gitlab/
List of Acceptable Values: http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html

Kind Regards
