### ISSUE TITLE
Upgrade to 8.9.5

### ISSUE THREAD

**Issue by Trefex** [jboxberger/synology-gitlab#3]
Hi,

Could you upgrade to 8.9.5 please?

Thanks,

**Comment by jboxberger** [comment]
Hi, the [sameersbn/gitlab](https://hub.docker.com/r/sameersbn/gitlab/) package on docker is not available in 8.9.5 yet. 
I think today or tommorrow they will release the 8.9.5 package and i will update asap.

Kind Regards

**Comment by Trefex** [comment]
Right. In that case, no worries :)

How do I upgrade the package eventually? Simply manually reinstall your package?

Thanks for that by the way, it works nicely.

**Comment by jboxberger** [comment]
I've updated the Package to 8.9.5.

Kind Regards
