### ISSUE TITLE
Backup/sql socket directory are not created in gitlab data dir

### ISSUE THREAD

**Issue by KirovAir** [jboxberger/synology-gitlab#30]
Hello,

First of all great work on this package!
Second, it seems that in the latest update(s) new directories are being created above the gitlab data dir. For example if my gitlab data dir is: /docker/gitlab
The following is being created:
/docker/backup
/docker/mysqld

While I would expect them to be at:
/docker/gitlab/backup
/docker/gitlab/mysqld

Thanks for reading. :)

**Comment by jboxberger** [comment]
Hi KirovAir, 

thanks for your information. the /docker/mysqld ist the folder for the MariaDB10 socket file  which is used for the mysql communictaion. The Database connection is not over the mysql port 3306, it goes over this file. This is stock from the original package so i decided not to change that. 

The second folder /docker/backup is from my custom backup script, which backups the whole /docker/giltab folder. If i put it inside /docker/gitlab then the backup script will backup the backup :-).

Everything is as it should be. The  /docker/backup folder is not used by gitlab so it can be removed if you not using the custom backup script. 

Kind Regards
Juri

**Comment by KirovAir** [comment]
Ah sweet. That explains it all! Thanks for your fast reaction! I am using your package since the start and it has been great.
Keep up the good work and have a nice evening!
