### ISSUE TITLE
Restore script does not work with MariaDB 10 and formerly installed MariaDB package

### ISSUE THREAD

**Issue by helmut-steiner** [jboxberger/synology-gitlab#33]
Hey Juri,
It's me again... ;)
When having both MariaDB and MariaDB10 package installed then deinstalling the MariaDB package the commands for mysql are not found any more as they used to point to the MariaDB installation. This means the restore script cannot find them and thus fails.

The MariaDB 10 mysql* commands are at: /usr/local/mariadb10/bin/

Just something I came across while migrating the different versions.
All the best,
Helmut

**Comment by jboxberger** [comment]
Hi Helmut,

there was a BUG in the restore script, please check if this is the Problem.

https://github.com/jboxberger/synology-gitlab/commit/9a035bda4034158db58973baf5d42b1f79a28186#diff-dbad4af2c2f96bc601e56bc0d5c8a77c

Kind Regards

**Comment by helmut-steiner** [comment]
Yes, that's it. :)
Sorry for the double issue.

**Comment by jboxberger** [comment]
No Problem, i think i need something kind of "Package" Version which identifies some progress, i've updated the binaries online but there is no way to see for you that they are newer. 
I thik i will make something like synology-gitlab-stock-aio-10.2.5-0001.spk and after each package change or fix i will increase the Package Version "synology-gitlab-stock-aio-10.2.5-0050.spk". 

I think this should work.

Thanks for reporting!

**Comment by helmut-steiner** [comment]
Yeah, sounds like a good idea!
Btw, have you thought of registering the packages in one of the synology community registers?

**Comment by jboxberger** [comment]
Yeah i would like to but i still can't get behind their creepy signing thing and can't get the toolkit running ... this thing is crazy... but my last attempt was a half year ago, things changes so i will give it another try as soon as i complete the PostgreSQL migration. I Still have some documentation an testing to do. I also will try to make a 9.4.4 MDB to PostgreSQL 9.4.4 upgrade Path to avoid the extra Jump from 9.4.4 to 10.2.5 MDB to 10.2.5 PostgreSQL.

I will be cool if the Update will work like the Original Package and also if user get notified if a newer Package is available. We will see :-).
