### ISSUE TITLE
Migration from synology-gitlab-jboxberger to this package.

### ISSUE THREAD

**Issue by s01ha** [jboxberger/synology-gitlab#34]
I'm using your synology-gitlab-jboxberger package and I've also updated it to the recent version 11.5.0-0102.

I would like to migrate it to this package.

Under your guidance for migration, synology-gitlab-jboxberger 11.5.0-0102 can be migrated to the version 11.5.0-0053 of this package, but I cannot find this version on this repository.

Is it possible to migrate mine to the version 11.5.1-0053 of this package?
Or where can I find the version 11.5.0-0053 of this package?

**Comment by jboxberger** [comment]
Hi,

sorry my bad. I will build a 11.5.0-0053 coming week and send you a meessage. 11.5.0-0102 to 11.5.1-0053 will not work. The Version has to be the same. 

If you need this urgently i can give you a not tested build but i recommend you to wait a few days for the tested version. 

Is this ok for you?

Kind Regards

**Comment by s01ha** [comment]
Thank you for your prompt reply.

 I have a backup of version 11.4.0-0102, so is it ok to migrate this version to the 11.4.0-0053 of this package?

**Comment by jboxberger** [comment]
It depends on how you created the backup. If you used the backup script from the 11.4.0-0102 this will not work. But if you created the backup with `sudo /usr/local/bin/docker exec -it synology_gitlab bash -c "sudo -u git -H bundle exec rake gitlab:backup:create RAILS_ENV=production CRON=1"` this should work and my tests were successfull. Please check the Notes [here](https://github.com/jboxberger/synology-gitlab#migration).

Please let me know how your migration worked.

Kind Regards

**Comment by s01ha** [comment]
I have a backup of 11.4.0-0102, so I'll follow the procedure below:

1) restore synology-gitlab-jboxberger package from backup of 11.4.0-0102.

2) backup using following command.
$ sudo /usr/local/bin/docker exec -it synology_gitlab bash -c "sudo -u git -H bundle exec rake gitlab:backup:create RAILS_ENV=production CRON=1"

3) remove and install new package "synology-gitlab"

4) restore from backup of 2)

Is it ok?

**Comment by jboxberger** [comment]
0.9) Make backup of current state with rake.
2.2) you need to save your backups from "/volume1/docker/gitlab-backup" because if something "bad" happens or you make a complete uninstall, your backups will be deleted too.

i highly recommend you not to restore your synology-gitlab-jboxberger to a lower version (11.4.0-0102). In the past there were some issues with the backup script from the "synology-gitlab-jboxberger" package. The backups script faled silently and the database dump was empty. So i recommend you to wait to get a smooth migration expirience.

I will release Gitlab synology-gitlab 11.5.0-0053 ASAP.

Kind Regards

**Comment by s01ha** [comment]
I got it.
Many thx :)

**Comment by jboxberger** [comment]
Hi,

if uploaded the [11.5.1-0102](https://github.com/jboxberger/synology-gitlab-jboxberger/releases) package so you can update the synology-gitlab-jboxberger 11.5.0-0102 to 11.5.1-0102 and then [migrate ](https://github.com/jboxberger/synology-gitlab#from-synology-gitlab-jboxberger-package-to-this-package)to the synology-gitlab 11.5.1-0053.

Wish you a happy year!
