### ISSUE TITLE
Need Help root password

### ISSUE THREAD

**Issue by ghost** [jboxberger/synology-gitlab#37]
Hello,

I use your gitlab package since a year, really nice to have an updated software, thanks for that.

I am sorry for that question, it is not a problem with your package.

I lost my root password, I don't find a way to reset it. Could you help me ?

**Comment by tobidemski** [comment]
Maybe the offical documentation helps you out.
https://docs.gitlab.com/ee/security/reset_root_password.html

**Comment by ghost** [comment]
Yes I find this page but It is more complicated with Docker.

I have try this command :

` sudo /usr/local/bin/docker exec -it synology_gitlab bash -c "sudo gitlab-rails console production"`

It return 

`sudo: gitlab-rails: command not found`

**Comment by tobidemski** [comment]
maybe this post helps you out:  https://github.com/sameersbn/docker-gitlab/issues/929#issuecomment-395087914

**Comment by ghost** [comment]
Yes, thanks. This is the complete command to launch the console : 

`sudo /usr/local/bin/docker exec -it synology_gitlab bash -c "sudo -u git -H bundle exec rails console production"`

**Comment by jboxberger** [comment]
I have tot thank too! Didn't knew the "trick", have done it laways with a native database update. I was about to write an small tutorial how to database update but you figured it out faster than me writing the tutorial. Nice! 👍
