### ISSUE TITLE
How to access the LDAP settings

### ISSUE THREAD

**Issue by thomvandevinlc** [jboxberger/synology-gitlab#39]
hey, not specifically an issue, more a question.
I'm trying to setup the LDAP configuration for my companies domain but I cant seem to enable ldap or even access the settings.
https://docs.gitlab.com/ee/administration/auth/how_to_configure_ldap_gitlab_ce/#example-gitlabrb-ldap

Any idea on how to access these setting and edit them?
I'm able to access the ruby-console and the docker-console through ssh, but I cant seem to edit or find the corresponding settings.

Sincerely,
Thom van de Vin

**Comment by jboxberger** [comment]
Hi,

have you tried this documetation yet? 
http://[your-nas]:30000/help/administration/auth/ldap

Yo will find it by pressing on the wrench icon and then on the questionmark near LDAP.

![image](https://user-images.githubusercontent.com/1545845/73129160-99454f00-3fdd-11ea-8886-c8f218455a72.png)

"NOTE: Note:
In GitLab Enterprise Edition Starter, you can configure multiple LDAP servers
to connect to one GitLab server.
For a complete guide on configuring LDAP with:

GitLab Community Edition, see
How to configure LDAP with GitLab CE.
Enterprise Editions, see
How to configure LDAP with GitLab EE. (STARTER ONLY)


To enable LDAP integration you need to add your LDAP server settings in
/etc/gitlab/gitlab.rb or /home/git/gitlab/config/gitlab.yml for Omnibus
GitLab and installations from source respectively."

Hope this helps. If not, let me know, maybe i can help anyhow.

Kind Regards
