### ISSUE TITLE
Can't edit any settings in Docker GUI

### ISSUE THREAD

**Issue by Trefex** [jboxberger/synology-gitlab#4]
When you try to edit the gitlab container, and save it, it complains that some environment variables are not correct, or not set appropriately.

I can edit the variables via SSH, but I would prefer if it works via the GUI too.

Can you have a look?

Thanks!

**Comment by jboxberger** [comment]
Hi, that's correct and is not a Bug. I use the docker GitLab Containers from https://hub.docker.com/r/sameersbn/gitlab/ (exactly the same as the original package from synology does). In this docker Containers there is no "edit" possible. All the configuration is file bases and will be (re)written during the install/update process. 

To extend the configuration files you can modify the postinst / postupgrade scripts. 

So far, the "edit" issue is a docker or maybe even synology issue, but i can't do anything about it. My package is just comfortable and enchanced installer / updater and i provide updates much more often than synology does.

Kind Regards
