### ISSUE TITLE
support request for Marvell Armada 370 88F6707

### ISSUE THREAD

**Issue by setlec** [jboxberger/synology-gitlab#41]
Hello there i've got a synology DS216se Nas and i would like to know if you could support your gitea /gitlab for this cpu architecture?

many thanks for your reply.

PS: i've left a copy of this message on you gitea

**Comment by caco3** [comment]
As you can see on https://www.synology.com/de-de/dsm/packages/Docker, your NAS does not support docker, therefore your request will never get fulfilled, at least with docker containers.
Also you need >2 GB RAM. I tried it with 2 GB and Gitlab did not even get ready to login. Only after I increased the RAM I got it running.

**Comment by setlec** [comment]
Thank you for your reply.

How did you increase the ram on this model it's soldered?

**Comment by caco3** [comment]
> Thank you for your reply.
> 
> How did you increase the ram on this model it's soldered?

I did not say that I have a `DS216se`! You will never get such complex application working on a starters NAS.
I have a `DS218+`. It has initially 2 GB RAM, but it has a free slot which can be officially fitted with up to 4 GB RAM (how ever 8 GB also work). If you need even more, you can replace the 2 GB in the internal slot with another 8 GB, but you have to open it and might void your warranty.
See https://www.windowscentral.com/how-upgrade-ram-synology-ds218 and https://nascompares.com/2019/05/09/synology-nas-unofficial-memory-upgrade-guide/

I have it running with 10 GB of RAM and never got to its limit, although I have several Docker containers running.

**Comment by jboxberger** [comment]
> Thank you for your reply.
> 
> How did you increase the ram on this model it's soldered?

Sorry for my late reply. If Upgrading the RAM is not an option for you or you just need a lightweight Visual GIT frontend similar to GitLab, then you maybe have a look a this package. If you use the default SQL DB this package, the whole application needs about 50 - 100M of RAM. 

https://github.com/jboxberger/synology-gitea-jboxberger

Kind Reagrds

**Comment by jboxberger** [comment]
@setlec : sorry but with the 256 MB RAM there is noway you will get this running. Even if you pass the installation Routine you will get a 502 error on page load. This happens even with 1GB ram and runs like crap. So 2GB is minimum and 4GB is recommended. You NAS RAM is soldered and therfore not upgradable. You're welcome to try out the Gitea package.

 is there still a task for me?

Kind Regards

**Comment by setlec** [comment]
@jboxberger Actually not nothing more to ask, Sir. I just hoped to be able to run gitlab. Thank you very much.
