### ISSUE TITLE
Web IDE is not working

### ISSUE THREAD

**Issue by fsutter** [jboxberger/synology-gitlab#46]
Hi,
on my installation the Web IDE feature is not working.
On the screen I have this message: Error while loading the project data. Please try again. 

This is the header of the page **https://gitlab.sutter.me/api/v4/projects/frederic%2Ftcp-proxy** that is in error:
HTTP/1.1 500 Internal Server Error
Date: Fri, 09 Oct 2020 06:32:22 GMT
Content-Type: application/json
Content-Length: 39
Cache-Control: no-cache
Vary: Origin
X-Request-Id: sYmmvrU8WP7
X-Runtime: 0.067327
Strict-Transport-Security: max-age=31536000;
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block

I'm using version 12.9.2-0055.
Does someone have an idea of the problem?

Many thanks in advance and kind regards,

Frédéric Sutter

**Comment by fsutter** [comment]
Hi again,

am I the only one having problems with Web IDE?

Thanks

Frédéric Sutter

**Comment by jboxberger** [comment]
Hello Frédéric,

sorry for my late reply. I've tested it with a clean install and have no issues. Do you have this issue on a specific project? Maybe you can try a new project with just a README so you can test if you issue is project specific.

![grafik](https://user-images.githubusercontent.com/1545845/96178968-73c3f100-0f30-11eb-82d4-acdf35c61193.png)

Kind Regards

**Comment by fsutter** [comment]
Hi,

thanks for taking the time to respond.
You're right with a new project it works like a charm.
Basically I have the error with all my old projects.
I had the problem already with stock 11.11.8-0055 and this was the reason I've updated to your package.
It had worked with a stock version before 11.11.8-0055 and suddenly no more.

Do you have an idea what I could do?
I assume that if I make a backup and a clean install, I'll have same issues, no?

Kind regards,

Frédéric

**Comment by fsutter** [comment]
Hi,
I finally managed to get it work by exporting all projects and reimporting them.
Something was broken.

regards,
