### ISSUE TITLE
Upgrade Issue from 12.0.3 to > 12.7

### ISSUE THREAD

**Issue by miralsoft** [jboxberger/synology-gitlab#48]
Hello,

I have upgraded from 12.0.3 to 13.9.3 with your help. I want to tell about my problems with the upgrading, for other people who have the same problems.

I have already given the fix for version> 12.3, but for the sake of completeness I will still write both fixes here. Both fixes are about the fact that index problems during the migration cancel the script and nothing works anymore. But that is not a problem, because here you only have to make changes to the database.

Here's how you go about solving this:
1. Connect to Synology via SSH (putty)
2. Get administrator rights:
_sudo -i_
3. Establish access to the Postgres database:
_sudo / usr / local / bin / docker exec --user = postgres -it synology_gitlab_postgresql bash -c "psql -d gitlab"_
4. Fix for update to 12.3 or higher (see https://gitlab.com/gitlab-org/gitlab/-/issues/33084):
_\ d snippets
DROP INDEX index_snippets_on_project_id;_
5. Fix for update to 12.7 or higher (see https://gitlab.com/gitlab-org/gitlab/-/merge_requests/31043):
_\ d ci_pipelines
DROP INDEX index_ci_pipelines_on_project_id;
DROP INDEX ci_pipelines_project_id_idx;_

After these two fixes, all upgrades went through without any problems in the same order as described on https://github.com/jboxberger/synology-gitlab#updates. 

Thank you again @jboxberger for your great work here.

**Comment by jboxberger** [comment]
Thank you for your contribution. I've moved your solution to the wiki.
Kind Regards
