### ISSUE TITLE
How to setup HTTPS?

### ISSUE THREAD

**Issue by Trefex** [jboxberger/synology-gitlab#5]
Hi,

Have you managed to get HTTPS to work?

I can't seem to ...

Any tips are welcome.

**Comment by jboxberger** [comment]
Hi,

you can setup HTTPS using this Info Page [here](https://hub.docker.com/r/sameersbn/gitlab/#ssl).
Just search for SSL / HTTPS and you will find the needed Information.

Kind Regards
