### ISSUE TITLE
Gitlab on DSM7

### ISSUE THREAD

**Issue by caco3** [jboxberger/synology-gitlab#51]
Since Synology dropped Gitlab support on **DSM7**, has anybody ever tested if the package from @jboxberger still works?
I know I could install Gitlab myself, but due to performance (see https://mlohr.com/gitlab-on-a-diskstation/#comment-33301) and simplicity reasons I prefer the all-in-one package.

**Comment by kosjason** [comment]
It's failed.
the "synology-gitlab-stock-aio-13.9.3-0068.dsm7.experimental.spk" can't install.
I also get "This package is not supported on the platform of DiskSatation or is incompatible with the current DSM version.".

**Comment by Hardcore-fs** [comment]
its all in this thread:
"Upgrade is not longer possible"

**Comment by caco3** [comment]
[Upgrade is not longer possible](https://github.com/jboxberger/synology-gitlab/issues/50)

**Comment by Hardcore-fs** [comment]
whats the point in providing a circular reference to close a problem ?

**Comment by caco3** [comment]
@Hardcore-fs You were so lazy to not even provide the issue as a link.
Since I had to search for it, I thought I would make it easier for others...
Why keeping a redundant issue open?

**Comment by Hardcore-fs** [comment]
I foolishly assumed that making circular references was a bad thing...
But I suspect my biggest mistake was to assume people were smart enough to use google or git indexes...
