### ISSUE TITLE
Timezone Option

### ISSUE THREAD

**Issue by tobidemski** [jboxberger/synology-gitlab#7]
It is possible to include the timezone into the setup?
I don't like it stop stop the service after the installation only to set up the timezone manuelly,

Greetz
D4rkiii

**Comment by jboxberger** [comment]
Hi D4rkiii,
i saw both of your tickets, technically it's possible. i will see what i can do for you.
I keep you up-to-date.

Kind Regards

**Comment by jboxberger** [comment]
Hi sorry for my late reply, I found a way to make you happy :-) and to unlock the container so you can edit/configure and export the settigs for the container in the docker app.

This update comes soon, i need to do some testing first.

Kind Regards

**Comment by jboxberger** [comment]
Solved in: 2016-10-16 - sameersbn/gitlab:8.12.6 (307.5MB)

**Comment by tobidemski** [comment]
Where can i set up the timezone?
Cant find any field to set it up in the latest version. (Upgrade / re-install)

**Comment by jboxberger** [comment]
The Gitlab constant you're searching for is **[GITLAB_TIMEZONE](https://hub.docker.com/r/sameersbn/gitlab/)** the possible values are available [here](http://api.rubyonrails.org/classes/ActiveSupport/TimeZone.html).

You have to add the Gitlab Constant to the Docker Gitlab-Container Enviroment Variables.
![gitlab02](https://cloud.githubusercontent.com/assets/1545845/19840556/8d239f4e-9ef8-11e6-8c70-237e60370301.png)

You can also edit the Ports Here
![gitlab](https://cloud.githubusercontent.com/assets/1545845/19840553/802c0c5e-9ef8-11e6-8fa5-5fd79a051ac7.png)

**Comment by tobidemski** [comment]
yeah i know it. Thought you included it into the setup wizard.

**Comment by jboxberger** [comment]
No Sorry modifying the setup is very hacky and instable, I also don't have possibilities like ajax in the API so i have to hardcode anything, translate it and test and so on. I try to keep the package as stock as possible. 

But for now you can modify anything from the docker backend and you can export and re-import your container modifications/settings. You need to apply / reimport your settings (if you have made custom changes) after every update. 

Hope your'e satisfied with this solution.
Kind Regards

**Comment by jboxberger** [comment]
FYI the new package version >= 10.1.4 will remeber any custom change to the environment variables, also the "GITLAB_TIMEZONE", and restore it on update. so you have to set the environment variable once.

Kind Regards

**Comment by tobidemski** [comment]
Hey, ich folgende schon deine letzten Beiträge und habe mitbekommen dass du das umgestellt hast! Danke dir für die Info!

Jetzt warte ich nur noch das du das mit > 10.3.x bzgl. MariaDB Problem hinbekommst :)

Weiter so!
