### ISSUE TITLE
Local / Container Port Definition

### ISSUE THREAD

**Issue by tobidemski** [jboxberger/synology-gitlab#8]
It would be nice if it is possible to define both ports in the setup.
I have to switch it all the times after an update to my other defined ports.

Example:
Gitlab Config:
Local port: 30000 | 30001
Internal port: 80 | 31
domain: gitlab.example.com
GITLAB_PORT: 80
GITLAB_SSH_PORT: 31

---

Reverse proxy setup:
Domain: gitlab.example.com
Port: 80 
to
Domain: localhost
Port: 30000

**Comment by jboxberger** [comment]
Solved in: 2016-10-16 - sameersbn/gitlab:8.12.6 (307.5MB)
